production = true

[mailserver]
host = "mail.wyvern.gg"
port = 587
username = "noreply@wyvern.gg"
password = "secret"
use_ssl = true
use_starttls = true

[database]

[database.postgres]
host = "localhost"
port = 5432
username = "wyvern"
password = "secret"
database = "wyvern"
ssl_mode = "Prefer"
timeout = 15
pooling = true

[api]

[api.registration]
invite_only = false

[utils]

[utils.cryptography]

[utils.cryptography.argon2]
time_cost = 10
memory_cost = 32768
lanes = 5
salt_length = 8
hash_length = 20